spring:
  datasource:
    username: admin
    password: win!3456
    url: jdbc:mysql://dietmanager.coodpx2moclq.us-east-2.rds.amazonaws.com:3306/diet_manager
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
